remote_theme: jekyll/minima@d4d779a
title: Title tbd
description: description tbd
author:
   name: fbossolan
   email: your-email@domain.com
minima:
  skin: dark

  social_links:
     - title: Minima Theme repository at GitHub
       icon: github
       url: "https://github.com/fbossolan"
     - title: Jekyll at X (formerly Twitter)
       icon: x-twitter
       url: "https://x.com/"
  nav_pages:
     - mqtt-antena.md
  hide_site_feed_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
