
title: Notes to self
author: fbossolan
description: >
   Just another software developer 

#remote_theme: jekyll/minima@d4d779a
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
   skin: dark
   nav_pages:
     - projects.md
   show_excerpts: false
   date_format: "%b-%d-%Y"
   social_links:
     - title: Minima Theme repository at GitHub
       icon: github
       url: "https://github.com/fbossolan"
     - title: Jekyll at X (formerly Twitter)
       icon: x-twitter
       url: "https://x.com/jekyllrb"
   hide_site_feed_link: true
